### ISSUE TITLE
Database Schema 

### ISSUE THREAD

**Issue by AdamYLiang** [willorwgl/Flamingo#2]
- [x] Explicitly list each table's index and foreign key underneath the table (in addition to in the column as you have it now).

**Users**
- [x] `username` should be instead firstname/lastname, consider making it two columns.
- [x] `email` should be always be present
- [x] `dob` should be always be present (to calculate age of user)
- [x] Add a column for `gender` to mimic the original app's signup 

**Profiles**
- [x] No need for profiles table. You can use AWS to handle all cover/profile photos and then make an association on the `Users` table. 

**Workplace**
- [x] No need for workplace table, we can hold that as a string in the Users if we really need it. Feel free to add it as a bonus. 

**Education**
- [x] No need for education table. Similar to workplace, it can be a bonus but it is fine to keep it as a string column on the users table. 

**Friends Join Table**
- [x] Consider adding a `status` column. I will be used to differentiate between  pending friend requests and actually friended users. 

**Post**
- [x] `body` should always be present 
- [x] What is the purpose of `user_id`? `author_id` should be sufficient. 
- [x] Consider looking into polymorphic associations if you want to have posts be able to handle photos and such. (https://guides.rubyonrails.org/association_basics.html#polymorphic-associations)

**Comment and Post Likes**
- [x] Make these a single `like` table that has a polymorphic association. See the link from above. 

Let me know if you have any questions or want to talk about these changes.

**Comment by willorwgl** [comment]
Done. I changed user_id to wall_id to make it more explicit. It should reference the wall that the post is posted on.

**Comment by AdamYLiang** [comment]
Nice changes! One last thing:

- [ ] Make `posts` a polymorphic association since users can post on profiles and comments. We can talk about this in person.
