### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by AdamYLiang** [willorwgl/Flamingo#3]
- [ ] Incomplete full slice of state, missing top level keys of `ui`, `errors`, `session`
- [ ] Include for seed data for a better visualization of the state. You should have more entries in the `users` and `friends` slices. 
- [ ] Need to have posts, comments, and likes. Remember that this is an entire state of your app at a given time. 

Make sure to look at you database schema and use that as a roadmap for making the state. Let me know if you have any questions.

**Comment by willorwgl** [comment]
wouldn't it be inefficient to fetch all users every time the user refreshes the page. I'm thinking of only fetching the current user info from the database and whenever that user visits another user's profile, it makes a new ajax request to the api.

**Comment by AdamYLiang** [comment]
Indeed that will be what we end up doing, but the sample state should be as if a user has been on the site and went to a couple user's profiles. We want to represent what our full sample state would look like in a slightly complex state of our app.
